name: verbose_share_world
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  animation_wrappers: ^3.0.0
  font_awesome_flutter: ^10.1.0
  pin_code_fields: ^7.0.0
  country_code_picker: ^2.0.1
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  modal_bottom_sheet: ^2.1.0
  amity_sdk: ^0.2.0
  provider: ^6.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icons/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile_pics/
    - assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
